GET http://localhost:4500/users

###
GET http://localhost:4500/view-payments/muk/2

###

POST http://localhost:4500/add-user
content-type: application/json

{
    "name":"joel",
    "group":"muk",
    "loan":100000,
    "id":2
}

###
POST http://localhost:4500/request-loan
content-type: application/json

{  "name":"joel",
    "group":"muk",
    "loan":100000,
    "id":2
}

###
POST http://localhost:4500/submit-payment
content-type: application/json

{
    "group":"muk",
    "id":2
}
